version: "3.5"
services:
  erigon:
    build:
      context: erigon
      args:
        UPSTREAM_VERSION: v2.57.0
    ports:
      - "30406:30406/tcp"
      - "30406:30406/udp"
    volumes:
      - "data:/home/erigon/.local/share"
    environment:
      P2P_PORT: 30406
      EXTRA_OPTs: "--http.api=engine,eth,erigon,web3,net,debug,trace,txpool"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 32768M
volumes:
  data: {}
